#include "MassingPromptGenerator.h"

#include "MassRuleParser.h"
#include "OpenAIMassingService.h"
#include "../core/Assets/AssetPaths.h"

#include <algorithm>
#include <cctype>
#include <fstream>
#include <iterator>
#include <sstream>

namespace Moon {
namespace Massing {

namespace {

std::string ReadUtf8TextFile(const std::string& path) {
    std::ifstream input(path, std::ios::binary);
    if (!input.is_open()) {
        return {};
    }

    std::string contents((std::istreambuf_iterator<char>(input)), std::istreambuf_iterator<char>());
    if (contents.size() >= 3 &&
        static_cast<unsigned char>(contents[0]) == 0xEF &&
        static_cast<unsigned char>(contents[1]) == 0xBB &&
        static_cast<unsigned char>(contents[2]) == 0xBF) {
        contents.erase(0, 3);
    }
    return contents;
}

std::string ToLower(std::string value) {
    std::transform(value.begin(), value.end(), value.begin(), [](unsigned char ch) {
        return static_cast<char>(std::tolower(ch));
    });
    return value;
}

bool ContainsAny(const std::string& haystack, std::initializer_list<const char*> needles) {
    for (const char* needle : needles) {
        if (haystack.find(needle) != std::string::npos) {
            return true;
        }
    }
    return false;
}

std::string ProjectPath(const std::string& relativePath) {
    return Moon::Assets::NormalizeSlashes(std::string(Moon::Assets::kProjectRootPath) + "/" + relativePath);
}

} // namespace

bool MassingPromptGenerator::GenerateFromPrompt(const std::string& userPrompt,
                                                const std::string& currentRuleJson,
                                                MassingPromptGenerationResult& outResult,
                                                std::string& outError) {
    outResult = MassingPromptGenerationResult();

    std::string hiddenContext;
    if (!BuildHiddenContext(hiddenContext, outError)) {
        return false;
    }

    if (OpenAIMassingService::IsConfigured()) {
        OpenAIMassingResponse aiResponse;
        if (!OpenAIMassingService::GenerateRuleJson(hiddenContext, userPrompt, currentRuleJson, aiResponse, outError)) {
            return false;
        }

        RuleSet validationRuleSet;
        std::string validationError;
        if (!MassRuleParser::ParseFromString(aiResponse.ruleJson, validationRuleSet, validationError)) {
            outError = "OpenAI returned invalid massing JSON: " + validationError;
            return false;
        }

        outResult.ruleJson = std::move(aiResponse.ruleJson);
        outResult.strategy = aiResponse.strategy.empty() ? "openai_generated" : aiResponse.strategy;
        outResult.notes = std::move(aiResponse.notes);
        outResult.notes.push_back("Generated by OpenAI model " + aiResponse.model + ".");
    } else {
        BuildingMassingIntent intent;
        std::string presetFile;
        std::vector<std::string> notes;
        if (!InferIntentFromPrompt(userPrompt, currentRuleJson, intent, presetFile, notes, outError)) {
            return false;
        }

        if (!presetFile.empty()) {
            if (!LoadCuratedPreset(presetFile, outResult.ruleJson, outError)) {
                return false;
            }
            outResult.strategy = "curated_preset";
            outResult.notes = std::move(notes);
        } else {
            if (!BuildingMassingPlanner::PlanToJsonString(intent, outResult.ruleJson, outError)) {
                return false;
            }
            outResult.strategy = "planner_generated";
            outResult.notes = std::move(notes);
        }
    }

    std::ostringstream summary;
    summary << "Injected hidden context from massing spec, building guide, and curated planned samples. "
            << "Prompt strategy: " << outResult.strategy << ".";
    outResult.hiddenContextSummary = summary.str();

    return true;
}

bool MassingPromptGenerator::BuildHiddenContext(std::string& outContext, std::string& outError) {
    const std::vector<std::string> hiddenFiles = {
        ProjectPath("docs/massing-rule-spec.md"),
        ProjectPath("docs/massing-building-guide.md"),
        Moon::Assets::BuildAssetPath("massing/planned_office_highrise.json"),
        Moon::Assets::BuildAssetPath("massing/planned_residential_tower.json"),
        Moon::Assets::BuildAssetPath("massing/planned_shopping_mall.json"),
        Moon::Assets::BuildAssetPath("massing/planned_vase_tower.json")
    };

    std::ostringstream combined;
    for (const std::string& file : hiddenFiles) {
        const std::string contents = ReadUtf8TextFile(file);
        if (contents.empty()) {
            outError = "Failed to load hidden massing context: " + file;
            return false;
        }
        combined << "\n=== " << file << " ===\n" << contents << "\n";
    }

    outContext = combined.str();
    return true;
}

bool MassingPromptGenerator::LoadCuratedPreset(const std::string& presetFile,
                                               std::string& outRuleJson,
                                               std::string& outError) {
    const std::string path = Moon::Assets::BuildAssetPath(std::string("massing/") + presetFile);
    outRuleJson = ReadUtf8TextFile(path);
    if (outRuleJson.empty()) {
        outError = "Failed to load curated preset: " + path;
        return false;
    }
    return true;
}

bool MassingPromptGenerator::InferIntentFromPrompt(const std::string& userPrompt,
                                                   const std::string& currentRuleJson,
                                                   BuildingMassingIntent& outIntent,
                                                   std::string& outPresetFile,
                                                   std::vector<std::string>& outNotes,
                                                   std::string& outError) {
    (void)currentRuleJson;
    if (userPrompt.empty()) {
        outError = "Prompt must not be empty";
        return false;
    }

    const std::string prompt = ToLower(userPrompt);

    if (ContainsAny(prompt, {"mall", "shopping mall", "shopping center", "retail"})) {
        outPresetFile = "planned_shopping_mall.json";
        outNotes.push_back("Matched prompt to curated shopping mall preset.");
        return true;
    }
    if (ContainsAny(prompt, {"vase", "flower vase", "waist tower"})) {
        outPresetFile = "planned_vase_tower.json";
        outNotes.push_back("Matched prompt to curated vase tower preset.");
        return true;
    }
    if (ContainsAny(prompt, {"oriental pearl", "pearl tower", "sphere tower", "observation tower"})) {
        outPresetFile = "planned_pearl_tower.json";
        outNotes.push_back("Matched prompt to curated pearl tower preset.");
        return true;
    }
    if (ContainsAny(prompt, {"twisted tower", "twisted highrise", "twist tower"})) {
        outPresetFile = "planned_twisted_highrise.json";
        outNotes.push_back("Matched prompt to curated twisted highrise preset.");
        return true;
    }
    if (ContainsAny(prompt, {"station", "transit hub", "terminal"})) {
        outPresetFile = "planned_transit_hub.json";
        outNotes.push_back("Matched prompt to curated transit hub preset.");
        return true;
    }
    if (ContainsAny(prompt, {"rotunda", "museum hall", "civic dome", "dome hall"})) {
        outPresetFile = "planned_civic_rotunda.json";
        outNotes.push_back("Matched prompt to curated civic rotunda preset.");
        return true;
    }
    if (ContainsAny(prompt, {"courtyard", "perimeter block", "mixed-use block"})) {
        outPresetFile = "planned_courtyard_block.json";
        outNotes.push_back("Matched prompt to curated courtyard block preset.");
        return true;
    }
    if (ContainsAny(prompt, {"villa", "house compound", "hillside house"})) {
        outPresetFile = "planned_hillside_villa.json";
        outNotes.push_back("Matched prompt to curated hillside villa preset.");
        return true;
    }
    if (ContainsAny(prompt, {"terrace tower", "terraced", "mixed use tower"})) {
        outPresetFile = "planned_terraced_mixed_use.json";
        outNotes.push_back("Matched prompt to curated terraced mixed-use preset.");
        return true;
    }

    BuildingMassingIntent intent;
    if (ContainsAny(prompt, {"office", "office tower", "highrise"})) {
        intent.archetype = "podium_tower";
        intent.buildingType = "office_tower";
        intent.style = "highrise_modern";
        intent.floors = ContainsAny(prompt, {"supertall", "very tall"}) ? 50 : 32;
        outNotes.push_back("Generated office tower intent from prompt.");
    } else if (ContainsAny(prompt, {"residential tower", "apartment tower", "residential"})) {
        intent.archetype = "tower";
        intent.buildingType = "residential_tower";
        intent.style = "warm_modern";
        intent.floors = 28;
        intent.twistDegrees = 3.0f;
        outNotes.push_back("Generated residential tower intent from prompt.");
    } else {
        intent.archetype = "podium_tower";
        intent.buildingType = "mixed_use_tower";
        intent.style = "modern";
        outNotes.push_back("Used default mixed-use tower intent.");
    }

    if (ContainsAny(prompt, {"taller", "higher"})) {
        intent.floors += 8;
        outNotes.push_back("Applied taller modifier.");
    }
    if (ContainsAny(prompt, {"shorter", "lower"})) {
        intent.floors = std::max(8, intent.floors - 8);
        outNotes.push_back("Applied shorter modifier.");
    }
    if (ContainsAny(prompt, {"wider", "broader"})) {
        intent.width += 6.0f;
        intent.depth += 4.0f;
        outNotes.push_back("Applied wider modifier.");
    }
    if (ContainsAny(prompt, {"slimmer", "narrower"})) {
        intent.width = std::max(18.0f, intent.width - 6.0f);
        intent.depth = std::max(16.0f, intent.depth - 4.0f);
        outNotes.push_back("Applied slimmer modifier.");
    }
    if (ContainsAny(prompt, {"twist more", "more twist", "twisted"})) {
        intent.twistDegrees = std::max(intent.twistDegrees, 12.0f);
        outNotes.push_back("Applied stronger twist.");
    }
    if (ContainsAny(prompt, {"no crown", "flat roof"})) {
        intent.crown = false;
        outNotes.push_back("Removed crown from generated intent.");
    }

    outIntent = intent;
    return true;
}

} // namespace Massing
} // namespace Moon
